import { useEffect, useState, type FormEvent, type JSX } from 'react';
import type { CreateCustomerInput, CrmCustomer } from '../main/crm/crmService';

export function CrmView({ token, listCustomers, createCustomer }: { token: string; listCustomers: (token: string) => Promise<CrmCustomer[]>; createCustomer: (token: string, input: CreateCustomerInput) => Promise<{ customerId: string }> }): JSX.Element {
    const [customers, setCustomers] = useState<CrmCustomer[]>([]);
    const [error, setError] = useState<string | null>(null);
    const [form, setForm] = useState<CreateCustomerInput>({ companyName: '', contactName: '', email: '', phone: '', tierId: '2f8c8d4e-8d28-4d4d-9f41-7a52c5f2e101' });
    const [saving, setSaving] = useState(false);
    useEffect(() => { void listCustomers(token).then(setCustomers).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Unable to load CRM.')); }, [token, listCustomers]);
    const save = async (event: FormEvent<HTMLFormElement>): Promise<void> => { event.preventDefault(); setSaving(true); try { await createCustomer(token, form); setForm({ companyName: '', contactName: '', email: '', phone: '', tierId: form.tierId }); await listCustomers(token).then(setCustomers); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to create customer.'); } finally { setSaving(false); } };
    return <section className="min-h-[calc(100vh-5rem)] bg-slate-100 px-6 pb-8 pt-6"><div className="mx-auto max-w-7xl"><h1 className="text-3xl font-bold text-slate-900">Customer relationships</h1><p className="mt-1 text-sm text-slate-500">Profiles, purchase history, loyalty points, and customer segments.</p>{error && <p className="mt-4 rounded-lg bg-red-50 p-3 text-red-700">{error}</p>}<form className="mt-6 grid gap-3 rounded-xl border border-slate-200 bg-white p-5 shadow-sm md:grid-cols-5" onSubmit={(event) => void save(event)}><input className="rounded-lg border border-slate-300 px-3 py-2" placeholder="Company" value={form.companyName ?? ''} onChange={(event) => setForm({ ...form, companyName: event.target.value })} /><input className="rounded-lg border border-slate-300 px-3 py-2" placeholder="Contact name *" required value={form.contactName} onChange={(event) => setForm({ ...form, contactName: event.target.value })} /><input className="rounded-lg border border-slate-300 px-3 py-2" placeholder="Email" type="email" value={form.email ?? ''} onChange={(event) => setForm({ ...form, email: event.target.value })} /><input className="rounded-lg border border-slate-300 px-3 py-2" placeholder="Phone" value={form.phone ?? ''} onChange={(event) => setForm({ ...form, phone: event.target.value })} /><button className="rounded-lg bg-orange-600 px-4 py-2 font-semibold text-white disabled:opacity-50" disabled={saving} type="submit">{saving ? 'Saving...' : 'Add customer'}</button></form><div className="mt-6 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Customer</th><th className="px-3 py-3">Email</th><th className="px-3 py-3">Phone</th><th className="px-3 py-3">Tier</th><th className="px-3 py-3 text-right">Orders</th><th className="px-3 py-3 text-right">Lifetime value</th><th className="px-5 py-3">Last purchase</th></tr></thead><tbody>{customers.map((customer) => <tr className="border-t border-slate-100" key={customer.customerId}><td className="px-5 py-4"><strong>{customer.displayName}</strong><div className="text-xs text-slate-500">{customer.tags.length ? customer.tags.join(', ') : 'No tags'} · {customer.pointsBalance} points</div></td><td className="px-3 py-4">{customer.email ?? '—'}</td><td className="px-3 py-4">{customer.phone ?? '—'}</td><td className="px-3 py-4">{customer.tierId}</td><td className="px-3 py-4 text-right">{customer.orderCount}</td><td className="px-3 py-4 text-right">${customer.lifetimeValue.toFixed(2)}</td><td className="px-5 py-4">{customer.lastPurchaseAt ? new Date(customer.lastPurchaseAt).toLocaleString() : 'No purchases'}</td></tr>)}</tbody></table></div></div></div></section>;
}
