import { useEffect, useState, type JSX } from 'react';
import type { CrmCustomer } from '../main/crm/crmService';

export function CrmView({ token, listCustomers }: { token: string; listCustomers: (token: string) => Promise<CrmCustomer[]> }): JSX.Element {
    const [customers, setCustomers] = useState<CrmCustomer[]>([]);
    const [error, setError] = useState<string | null>(null);
    useEffect(() => { void listCustomers(token).then(setCustomers).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Unable to load CRM.')); }, [token, listCustomers]);
    return <section className="min-h-[calc(100vh-5rem)] bg-slate-100 px-6 pb-8 pt-6"><div className="mx-auto max-w-7xl"><h1 className="text-3xl font-bold text-slate-900">Customer relationships</h1><p className="mt-1 text-sm text-slate-500">Profiles, purchase history, loyalty points, and customer segments.</p>{error && <p className="mt-4 rounded-lg bg-red-50 p-3 text-red-700">{error}</p>}<div className="mt-6 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Customer</th><th className="px-3 py-3">Tier</th><th className="px-3 py-3">Tags</th><th className="px-3 py-3 text-right">Orders</th><th className="px-3 py-3 text-right">Lifetime value</th><th className="px-5 py-3">Last purchase</th></tr></thead><tbody>{customers.map((customer) => <tr className="border-t border-slate-100" key={customer.customerId}><td className="px-5 py-4"><strong>{customer.displayName}</strong><div className="text-xs text-slate-500">{customer.email ?? 'No email'}{customer.phone ? ` · ${customer.phone}` : ''}</div></td><td className="px-3 py-4">{customer.tierId}</td><td className="px-3 py-4">{customer.tags.length ? customer.tags.join(', ') : '—'}<div className="text-xs text-amber-700">{customer.pointsBalance} loyalty points</div></td><td className="px-3 py-4 text-right">{customer.orderCount}</td><td className="px-3 py-4 text-right">${customer.lifetimeValue.toFixed(2)}</td><td className="px-5 py-4">{customer.lastPurchaseAt ? new Date(customer.lastPurchaseAt).toLocaleString() : 'No purchases'}</td></tr>)}</tbody></table></div></div></div></section>;
}
