import { useEffect, useState, type JSX } from 'react';
import type { EmployeeSummary } from '../main/employees/employeeService';

export function EmployeesView({ token, list, clockIn, clockOut }: { token: string; list: (token: string) => Promise<EmployeeSummary[]>; clockIn: (token: string) => Promise<void>; clockOut: (token: string) => Promise<void> }): JSX.Element {
    const [employees, setEmployees] = useState<EmployeeSummary[]>([]);
    const [error, setError] = useState<string | null>(null);
    const refresh = (): void => { void list(token).then(setEmployees).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Unable to load employees.')); };
    useEffect(() => { refresh(); }, [token]);
    const toggleShift = async (employee: EmployeeSummary): Promise<void> => { try { if (employee.openShiftStart) await clockOut(token); else await clockIn(token); refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to update shift.'); } };
    return <section className="min-h-[calc(100vh-5rem)] bg-slate-100 px-6 pb-8 pt-6"><div className="mx-auto max-w-7xl"><div className="flex items-end justify-between"><div><h1 className="text-3xl font-bold text-slate-900">Employee management</h1><p className="mt-1 text-sm text-slate-500">Permissions, shift status, and individual sales performance.</p></div><button className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-semibold" type="button" onClick={refresh}>Refresh</button></div>{error && <p className="mt-4 rounded-lg bg-red-50 p-3 text-red-700">{error}</p>}<div className="mt-6 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Employee</th><th className="px-3 py-3">Role</th><th className="px-3 py-3">Shift</th><th className="px-3 py-3 text-right">Sales</th><th className="px-5 py-3 text-right">Sales total</th><th><span className="sr-only">Action</span></th></tr></thead><tbody>{employees.map((employee) => <tr className="border-t border-slate-100" key={employee.userId}><td className="px-5 py-4"><strong>{employee.displayName}</strong><div className="text-xs text-slate-500">{employee.username}</div></td><td className="px-3 py-4 capitalize">{employee.role}</td><td className="px-3 py-4">{employee.openShiftStart ? `Clocked in ${new Date(employee.openShiftStart).toLocaleTimeString()}` : 'Off shift'}</td><td className="px-3 py-4 text-right">{employee.salesCount}</td><td className="px-5 py-4 text-right">${employee.salesTotal.toFixed(2)}</td><td className="pr-5 text-right"><button className="rounded-lg border border-slate-300 px-3 py-2 text-xs font-semibold" type="button" onClick={() => void toggleShift(employee)}>{employee.openShiftStart ? 'Clock out' : 'Clock in'}</button></td></tr>)}</tbody></table></div></div></div></section>;
}
